import ArticleTemplate from "@/components/ArticleTemplate";
const paragraphs = [
"Dok Francusku potresaju protesti srednjoškolaca i studenata, iskustvo studentskog pokreta u Srbiji našlo se u francuskoj javnoj debati. Noé Girardot-Champsaur, gost emisije „28 minutes“ televizije ARTE, u objavi povodom svog gostovanja ukazao je na politički odgovor srpskih studenata vlastima koje nisu reagovale na njihove zahteve.",
"„Vlada bi trebalo da obrati pažnju na zahteve srednjoškolaca. U Srbiji, suočeni sa vladom koja je ostala gluva na demonstracije, studenti su formirali građansku listu koja danas dostiže 44 odsto u anketama“, napisao je Girardot-Champsaur na Instagramu. Podatak od 44 odsto navodimo kao njegovu tvrdnju, ne kao nezavisno potvrđen rezultat istraživanja.",
{type:"heading" as const,text:"Pariz: protesti i sukobi sa policijom"},
"Protesti zbog stanja u obrazovanju nastavili su se 8. oktobra. Francuski mediji izvestili su o blokadama škola i sukobima u Parizu, gde je na Trgu Bastilje policija upotrebila vodeni top. Organizatori zahtevaju više nastavnika, bolje uslove školovanja i promene obrazovne politike.",
"Protesti su izazvali raspravu i o postupanju policije prema maloletnim demonstrantima. Obim okupljanja i broj privedenih razlikuju se zavisno od datuma i izvora, zbog čega ih ne treba mešati sa podacima sa ranijih protesta.",
{type:"heading" as const,text:"Zašto je pomenuta Srbija"},
"U poruci francuskim vlastima Girardot-Champsaur koristi Srbiju kao primer mogućih političkih posledica ignorisanja zahteva mladih. Ta veza je dokumentovana njegovom javnom objavom, ali sama po sebi ne dokazuje da su francuski protesti nastali po uzoru na srpske.",
"Značajno je to što se iskustvo srpskog studentskog pokreta koristi kao argument u francuskoj debati o odnosu države prema mladima. To je međunarodni odjek protesta u Srbiji koji zaslužuje pažnju i bez preuveličavanja.",
{type:"heading" as const,text:"Izvori i napomena"},
"ARTE, „28 minutes“, emisija „Jeunesse en colère : comment y répondre ?“, 5. oktobar 2026; javna Instagram objava @noe_girardotchampsaur; TF1, izveštaj o upotrebi vodenog topa na Trgu Bastilje, 8. oktobar 2026. Citirana izjava potiče iz opisa Instagram objave, ne iz nezavisno proverenog transkripta emisije.",
];
export default function FrancuskaProtestiArteStudenti(){return <ArticleTemplate path="/srbija/francuska-protesti-arte-srpski-studenti" sectionLabel="SVET · FRANCUSKA" title="Francuska na nogama, a na ARTE-u se govori o srpskim studentima" dateLabel="8. OKTOBAR 2026." deck="Dok Francusku potresaju protesti mladih, Noé Girardot-Champsaur u javnoj objavi povodom gostovanja na ARTE-u ukazuje na iskustvo srpskih studenata i njihov politički odgovor vlastima." imageSrc="/news/france-serbian-protests.jpg" imageBeforeDeck imageHeightClass="h-auto" imageAlt="Grafički vizual Novog Talasa u bojama francuske zastave, sa naslovom Francuska na nogama." imageCredit="Ilustracija: Novi Talas / AI (nije fotografija protesta)" paragraphs={paragraphs} backHref="/srbija" backLabel="← Nazad na Srbiju"/>;}