import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Link } from "wouter";
import { useTheme } from "@/contexts/ThemeContext";
import GeopolitikaIndexLegacy from "./GeopolitikaIndexLegacy";
const FEATURED=[{href:"/geopolitika/afd-menja-politicku-mapu-nemacke-ruski-gas-se-vraca-u-igru",title:"AfD menja političku mapu Nemačke — a ruski gas se vraća u igru",description:"AfD je sa 38,2 odsto pobedio u Meklenburgu-Zapadnoj Pomeraniji, dok se ruski gas i Nord Stream vraćaju u nemačku političku raspravu.",imageSrc:"/news/afd-weidel-germany.jpg",imageAlt:"Alis Vajdel uz nemačku zastavu i obeležja AfD-a."},{href:"/geopolitika/amerika-nije-dobila-grenland-dobija-ono-zbog-cega-ga-je-zelela",title:"Amerika nije dobila Grenland. Dobija ono zbog čega ga je želela",description:"SAD, Danska i Grenland pripremaju sporazum o jačanju bezbednosti na Arktiku. Suverenitet se ne menja, ali strateška važnost ostrva ubrzano raste.",imageSrc:"/news/greenland-us-arctic.jpg",imageAlt:"Editorial ilustracija Grenlanda."},{href:"/geopolitika/da-li-se-menja-mapa-ujedinjenog-kraljevstva",title:"Da li se menja mapa Ujedinjenog Kraljevstva? Tri nacionalna pokreta zajedno otvorila pitanje samoopredeljenja",description:"SNP, Plaid Cymru i Sinn Féin potpisali su u Kardifu memorandum o samoopredeljenju.",imageSrc:"/news/uk-self-determination-flags.jpg",imageAlt:"Zastave Škotske i Velsa uz simbol Severne Irske."},{href:"/geopolitika/amerika-prvi-put-javno-potvrdila-imamo-oruzje-u-orbiti",title:"Amerika prvi put javno potvrdila: imamo oružje u orbiti",description:"SAD su prvi put otvoreno potvrdile da već imaju oružane sisteme raspoređene u Zemljinoj orbiti.",imageSrc:"https://media.defense.gov/2026/Sep/15/2003997876/2000/2000/0/260914-F-JJ904-1095.JPG",imageAlt:"Američki sekretar Ratnog vazduhoplovstva Troy Meink."}] as const;
function FeaturedStory({story,priority=false}:{story:(typeof FEATURED)[number];priority?:boolean}){const{theme}=useTheme();const d=theme==="dark";return <article><Link href={story.href} className="no-underline"><div className="border mb-4 overflow-hidden" style={{borderColor:d?"#2a2a2e":"#eee",backgroundColor:d?"#1a1c22":"#f7f7f7"}}><img src={story.imageSrc} alt={story.imageAlt} className="w-full h-[260px] md:h-[360px] object-cover object-center block" loading={priority?"eager":"lazy"}/></div><span className="kicker">Geopolitika</span><h2 className="mt-2 text-[24px] md:text-[32px] font-bold leading-[1.15]" style={{fontFamily:"'Playfair Display', serif",color:d?"#e0ddd5":"#111"}}>{story.title}</h2><p className="mt-2 text-[15px] leading-[1.6]" style={{fontFamily:"'Crimson Pro', serif",color:d?"#9a978f":"#555"}}>{story.description}</p><div className="mt-3 text-[12px] font-semibold uppercase tracking-[0.08em]" style={{color:d?"#d9bf7a":"#8B0000"}}>Otvori tekst →</div></Link></article>}
function FeaturedStories(){return <div className="space-y-10">{FEATURED.map((s,i)=><FeaturedStory key={s.href} story={s} priority={i===0}/>)}</div>}
export default function GeopolitikaIndexWithOrbital(){const[host,setHost]=useState<HTMLDivElement|null>(null);useEffect(()=>{const candidates=Array.from(document.querySelectorAll("main div"));const grid=candidates.find(el=>el.classList.contains("grid")&&el.classList.contains("grid-cols-1")&&el.classList.contains("gap-10"));if(!grid)return;const mount=document.createElement("div");mount.className="md:col-span-2";grid.prepend(mount);setHost(mount);return()=>{mount.remove();setHost(null)}},[]);return <><GeopolitikaIndexLegacy/>{host?createPortal(<FeaturedStories/>,host):null}</>}
