/*
 * DESIGN: "Diplomatska Klasika" v4
 */
import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useTheme } from "@/contexts/ThemeContext";
import { HOME_ARTICLES } from "./homeArticles";

const HERO_ARTICLE = {
  href: "/geopolitika/afd-menja-politicku-mapu-nemacke-ruski-gas-se-vraca-u-igru",
  category: "GEOPOLITIKA · NEMAČKA",
  title: "AfD menja političku mapu Nemačke — a ruski gas se vraća u igru",
  description: "AfD je sa 38,2 odsto pobedio u Meklenburgu-Zapadnoj Pomeraniji. U isto vreme, ruski gas i Nord Stream vraćaju se u nemačku političku raspravu.",
  imageSrc: "/news/afd-weidel-germany.svg?v=2",
  imageAlt: "Editorial vizual o AfD-u i promeni političke mape Nemačke.",
};
const ARTICLES = HOME_ARTICLES;
function useFadeIn(){const ref=useRef<HTMLDivElement>(null);const[visible,setVisible]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setVisible(true);o.unobserve(el)}},{threshold:.1});o.observe(el);return()=>o.disconnect()},[]);return{ref,visible}}
function FadeIn({children,className=""}:{children:React.ReactNode;className?:string}){const{ref,visible}=useFadeIn();return <div ref={ref} className={className} style={{opacity:visible?1:0,transform:visible?"translateY(0)":"translateY(16px)",transition:"opacity 0.7s ease, transform 0.7s ease"}}>{children}</div>}
interface SmallArticleCardProps{category:string;href:string;title:string;description:string;imageSrc:string;imageAlt:string;variant?:"split"|"tile"}
function SmallArticleCard({category,href,title,description,imageSrc,imageAlt,variant="split"}:SmallArticleCardProps){const{theme}=useTheme();const d=theme==="dark";if(variant==="tile")return <article className="overflow-hidden rounded-xl border" style={{borderColor:d?"#2a2a2e":"#eee",backgroundColor:d?"#17191f":"#fff"}}><Link href={href} className="block no-underline"><img src={imageSrc} alt={imageAlt} className="w-full h-[120px] object-cover block" loading="lazy"/><div className="p-3"><span className="kicker">{category}</span><h3 className="mt-1 text-[17px] font-bold leading-[1.2]" style={{fontFamily:"'Lora', Georgia, serif",color:d?"#e0ddd5":"#111"}}>{title}</h3></div></Link></article>;return <article className="grid grid-cols-[1fr_112px] min-[390px]:grid-cols-[1fr_118px] gap-4 items-start"><div><span className="kicker">{category}</span><h3 className="mt-1 text-[19px] min-[390px]:text-[20px] font-bold leading-[1.18]" style={{fontFamily:"'Lora', Georgia, serif",color:d?"#e0ddd5":"#111"}}><Link href={href} className="headline-link">{title}</Link></h3><p className="hidden">{description}</p></div><Link href={href}><img src={imageSrc} alt={imageAlt} className="w-[112px] h-[84px] object-cover border rounded-md" loading="lazy"/></Link></article>}
function DesktopSideStory({article}:{article:(typeof ARTICLES)[number]}){const{theme}=useTheme();const d=theme==="dark";return <article className="grid grid-cols-[1fr_104px] gap-4 border-b pb-4"><div><span className="kicker">{article.category}</span><h3 className="mt-1 text-[18px] font-bold leading-[1.18]" style={{fontFamily:"'Lora', Georgia, serif",color:d?"#e0ddd5":"#111"}}><Link href={article.href} className="headline-link">{article.title}</Link></h3></div><Link href={article.href}><img src={article.imageSrc} alt={article.imageAlt} className="w-[104px] h-[72px] object-cover rounded-md border"/></Link></article>}
function DesktopTileStory({article}:{article:(typeof ARTICLES)[number]}){const{theme}=useTheme();const d=theme==="dark";return <article><Link href={article.href}><img src={article.imageSrc} alt={article.imageAlt} className="w-full aspect-[16/9] object-cover rounded-lg border"/></Link><span className="kicker block mt-3">{article.category}</span><h3 className="mt-2 text-[22px] font-bold leading-[1.12]" style={{fontFamily:"'Lora', Georgia, serif",color:d?"#e0ddd5":"#111"}}><Link href={article.href} className="headline-link">{article.title}</Link></h3></article>}
export default function Home(){const{theme}=useTheme();const d=theme==="dark";return <div className="min-h-screen flex flex-col" style={{backgroundColor:d?"#111318":"#fff"}}><Header/><main className="pt-0 pb-12 md:pt-7 md:pb-14 flex-1"><div className="max-w-[1200px] mx-auto px-5 md:px-8"><div className="md:hidden"><FadeIn className="mb-5"><article className="flex flex-col"><Link href={HERO_ARTICLE.href} className="block no-underline -mx-5 order-first mb-4"><div className="relative w-full overflow-hidden aspect-[2/1]"><img src={HERO_ARTICLE.imageSrc} alt={HERO_ARTICLE.imageAlt} className="w-full h-full object-cover block" fetchPriority="high"/></div></Link><span className="kicker block mb-2">{HERO_ARTICLE.category}</span><h2 className="mt-2 mb-2 text-[25px] min-[390px]:text-[27px] font-bold leading-[1.06]" style={{fontFamily:"'Playfair Display', Georgia, serif",color:d?"#e0ddd5":"#111"}}><Link href={HERO_ARTICLE.href} className="headline-link">{HERO_ARTICLE.title}</Link></h2><p className="text-[15px] min-[390px]:text-[16px] leading-[1.48] line-clamp-2">{HERO_ARTICLE.description}</p></article></FadeIn><hr className="editorial-divider mb-5"/><div className="mb-10"><div className="flex flex-col gap-5"><SmallArticleCard {...ARTICLES[0]}/><hr/><SmallArticleCard {...ARTICLES[1]}/><hr/><SmallArticleCard {...ARTICLES[2]}/><hr/><div className="grid grid-cols-1 min-[420px]:grid-cols-2 gap-4">{ARTICLES.slice(3,8).map((a)=><SmallArticleCard key={a.href} variant="tile" {...a}/>)}</div></div></div></div><div className="hidden md:block"><FadeIn className="mb-9"><section className="grid grid-cols-[minmax(0,1.65fr)_minmax(300px,0.85fr)] gap-8 items-start border-b pb-8"><article><Link href={HERO_ARTICLE.href}><img src={HERO_ARTICLE.imageSrc} alt={HERO_ARTICLE.imageAlt} className="w-full h-[340px] lg:h-[390px] object-cover rounded-xl border" fetchPriority="high"/></Link><span className="kicker block mt-4">{HERO_ARTICLE.category}</span><h1 className="mt-2 text-[40px] lg:text-[48px] font-bold leading-[1.02]" style={{fontFamily:"'Playfair Display', Georgia, serif"}}><Link href={HERO_ARTICLE.href} className="headline-link">{HERO_ARTICLE.title}</Link></h1><p className="mt-4 max-w-[720px] text-[18px] leading-[1.48]">{HERO_ARTICLE.description}</p></article><aside className="flex flex-col gap-4"><div className="text-[11px] font-semibold tracking-[0.18em] uppercase border-b pb-3">Najnovije</div>{ARTICLES.slice(0,3).map(a=><DesktopSideStory key={a.href} article={a}/>)}</aside></section></FadeIn><FadeIn><section className="grid grid-cols-2 lg:grid-cols-3 gap-8">{ARTICLES.slice(3,8).map(a=><DesktopTileStory key={a.href} article={a}/>)}</section></FadeIn></div></div></main><Footer/></div>}
